services:
  postgres:
    image: postgres:16-alpine
    container_name: task-postgres-container
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: raiderUser
      POSTGRES_PASSWORD: raiderPass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: task-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: task-rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
    container_name: task-backend-container
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  consumer:
    build:
      context: ./consumer
    container_name: task-consumer-container
    depends_on:
      - rabbitmq
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend-container
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data:
